spring:
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug
